---
- name: telegraf
  hosts: all
  become: yes
  become_user: root

  vars:
    telegraf_install_url: "https://dl.influxdata.com/telegraf/releases/telegraf_1.11.2-1_amd64.deb"
    telegraf_sha256sum: "39ef98f2ae427c480f8f0ca55e941acf061f208f67f1ae73d6e74ea926f819ef"
    telegraf_hostname: "{{ deploy_host }}"
  tasks:

    # install
    - name: download telegraf package
      get_url:
        url: "{{ telegraf_install_url }}"
        dest: /tmp/telegraf-ansible-download.deb
        sha256sum: "{{ telegraf_sha256sum }}"

    - name: install downloaded telegraf package
      apt:
        deb: /tmp/telegraf-ansible-download.deb
        state: present
      register: apt_result
      until: apt_result is success
      retries: 2
      delay: 5

    - name: adding telegraf user to group adm (allow to read log files)
      user:
        name: telegraf
        groups: adm
        append: yes

    - file: path=/opt/telegraf state=directory

    - name: install pip3
      apt: name=python3-pip state=present

    - name: install python packages
      shell: pip3 install requests==2.22.0

    # wallet
    - name: install wallet telegraf script
      template:
        src: templates/telegraf_wallet.py
        dest: /opt/telegraf/telegraf_wallet.py
        mode: 0755

    - name: install telegraf wallet config
      template:
        src: templates/telegraf_wallet.conf.j2
        dest: /etc/telegraf/telegraf.d/wallet.conf

    # sshd
    - name: install pam sshd script
      template:
        src: templates/pam_sshd.py
        dest: /opt/telegraf/pam_sshd.py
        mode: 0700

    - name: add to pam conf
      lineinfile: dest=/etc/pam.d/sshd line="session required pam_exec.so /opt/telegraf/pam_sshd.py --output /opt/telegraf/sshd/sshd.json"

    - name: install sshd telegraf script
      template:
        src: templates/telegraf_sshd.py
        dest: /opt/telegraf/telegraf_sshd.py
        mode: 0755

    - name: install telegraf sshd config
      template:
        src: templates/telegraf_sshd.conf.j2
        dest: /etc/telegraf/telegraf.d/sshd.conf

    # nginx config
    - name: install telegraf nginx config
      template:
        src: templates/telegraf_nginx.conf.j2
        dest: /etc/telegraf/telegraf.d/nginx.conf

    # general config
    - name: install telegraf config
      template:
        src: templates/telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf

    - name: restart telegraf
      service: name=telegraf state=restarted
